DELETE FROM _systemlogs;
DELETE FROM _contextPosition;
INSERT INTO _contextPosition (cName, cPosition, caption) VALUES 
			('login', 1, 'User Accounts Management'), 
			('login_create', 2, 'Create User Account'),
			('login_read', 3, 'View User Account'), 
			('login_update', 4, 'Update User Account'), 
			('login_delete', 5, 'Delete User Account'),
			('login_search', 6, 'Search User Accounts'),
			('profile', 7, 'General System Settings'),
			('profile_update', 8, 'Update System Settings'), 
			('profile_read', 9, 'View System Settings'),
			('group', 10, 'General Group Operation'),
			('group_create',11, 'Create a User Group'),
			('group_read', 12, 'View a User Group'),
			('group_update', 13, 'Update a User Group'),
			('group_delete', 14, 'Delete a User Group'),
			('group_search', 15, 'Search User Groups'),
			('jobtitle', 16, 'General Jobtitle Operations'),
			('jobtitle_create', 17, 'Create a User Jobtitle'),
			('jobtitle_read', 18, 'View a User Jobtitle'),
			('jobtitle_update', 19, 'Update a User Jobtitle'),
			('jobtitle_delete', 20, 'Delete a User Jobtitle'),
			('jobtitle_search', 21, 'Search User Jobtitles'),
			('menu_mysystem', 22, 'My System Menu'),
			('menu_users', 23, 'System Users'),
			('update_my_login', 24, 'Update My User Accounts'),
			('firewall', 25, 'Firewall/Authorization Management'),
			('firewall_update', 26, 'Update Firewall'),
			('firewall_read', 27, 'View Firewalls'),
			('system_lastresort_donotcare', 28, 'System Decision on Do not care'),
			('systemlogs', 29, 'General System Logs Management'),
			('systemlogs_search', 30, 'Search System Logs'),
			('patient', 31, 'Patient Management'),
			('patient_create', 32, 'Create A Patient'),
			('patient_read', 33, 'Details of A Patient'),
			('patient_update', 34, 'Update Patient'),
			('patient_delete', 35, 'Delete a Patient'),
			('patient_search', 36, 'Search Patients'),
			('servicecategory', 37, 'Service Category Management'),
			('servicecategory_create', 38, 'Create Service Category'),
			('servicecategory_read', 39, 'Details of a Service Category'),
			('servicecategory_update', 40, 'Update Service Category'),
			('servicecategory_delete', 41, 'Delete a Service Category'),
			('servicecategory_search', 42, 'Search Service Categories'),
			('menu_finance', 43, 'Finance Menu'),
			('service', 44, 'Service Management'),
			('service_create', 45, 'Create Service'),
			('service_read', 46, 'Details of a Service'),
			('service_update', 47, 'Update Service'),
			('service_delete', 48, 'Delete a Service'),
			('service_search', 49, 'Search Services'),
			('hospital', 50, 'Hospital Settings Management'),
			('hospital_read', 51, 'Details/View Hospital Settings'),
			('hospital_update', 52, 'Update Hospital Settings'),
			('notificationmanager', 53, 'Notification Manager Services'),
			('notificationmanager_create', 54, 'Create a New Notification Manager'),
			('notificationmanager_read', 55, 'Details/View a Notification Manager'),
			('notificationmanager_update', 56, 'Update a Notification Manager'),
			('notificationmanager_delete', 57, 'Delete a Notification Manager'),
			('notificationmanager_search', 58, 'Search a Notification Manager'),
			('patientinvoice', 59, 'General Patient Invoice Management'),
			('patientinvoice_create', 60, 'Raise/Create Patient Invoice'),
			('patientinvoice_read', 61, 'Deails/View Patient Invoice'),
			('patientinvoice_search', 62, 'Search Patient Invoice'),
			('patientreceipt', 63, 'General Patient Receipt Management'),
			('patientreceipt_create', 64, 'Issue/Create a Patient Receipt'),
			('patientreceipt_read', 65, 'Details/View a Patient Receipt'),
			('patientreceipt_search', 66, 'Search a Patient Receipt'),
			('triage', 67, 'Triage [Vital Signs] Management'),
			('triage_create', 68, 'Triage [Vitals Signs] create or record'),
			('triage_read', 69, 'Triage [Vital Signs] view details'),
			('triage_search', 70, 'Triage [Vital Signs] Search'),
			('systemuser', 71, 'General System User Management'),
			('systemuser_create', 72, 'Create a System User'),
			('systemuser_read', 73, 'Details/View of a System User'),
			('systemuser_update', 74, 'Update a System User'),
			('systemuser_delete', 75, 'Delete a System User'),
			('systemuser_search', 76, 'Search a System User'),
			('medicaldoctor', 77, 'General Medical Doctor Management'),
			('medicaldoctor_create', 78, 'Create or Add a Medical Doctor'),
			('medicaldoctor_read', 79, 'Details/View a Medical Doctor'),
			('medicaldoctor_update', 80, 'Update Medical Doctor data'),
			('medicaldoctor_delete', 81, 'Delete or Remove medical Doctor'),
			('medicaldoctor_search', 82, 'Search Medical Doctor'),
			('medicaldoctor_consult', 83, 'Patient Consultation'),
			('examination', 84, 'Laboratory Examination'),
			('examination_ultrasound', 85, 'Ultra Sound Examination'),
			('examination_xray_plain', 86, 'Plain X-RAY Examination'),
			('examination_wetlab', 87, 'Wet/Chemical Laboratory Examination'),
			('pharmaceuticaldrug', 88, 'General Drugs Management'),
			('pharmaceuticaldrug_create', 89, 'Create a Drug'),
			('pharmaceuticaldrug_read', 90, 'Details/View a Drug'),
			('pharmaceuticaldrug_update', 91, 'Update Drug'),
			('pharmaceuticaldrug_delete', 92, 'Delete or remove a drug'),
			('pharmaceuticaldrug_search', 93, 'Search a Drug'),
			('menu_admission', 94, 'Admission Menu'),
			('ward', 95, 'General Wards Management'),
			('ward_create', 96, 'Create a New Ward'),
			('ward_read', 97, 'Details/View a Ward'),
			('ward_update', 98, 'Update a ward'),
			('ward_delete', 99, 'Delete a ward'),
			('ward_search', 100, 'Search a ward'),
			('room', 101, 'General Rooms Management'),
			('room_create', 102, 'Create a New Room'),
			('room_read', 103, 'Details/View a Room'),
			('room_update', 104, 'Update a Room'),
			('room_delete', 105, 'Delete a Room'),
			('room_search', 106, 'Search a Room'),
			('bed', 107, 'General Beds Management'),
			('bed_create', 108, 'Create a New Bed'),
			('bed_read', 109, 'Details/View a Bed'),
			('bed_update', 110, 'Update a Bed'),
			('bed_delete', 111, 'Delete a Bed'),
			('bed_search', 112, 'Search a Bed'),
			('medicaldoctor_approve_results', 113, 'Approve Examination Results'),
			('medicaldoctor_repeat_examination', 114, 'Repeat Examination Request'),
			('nursestation', 115, 'Nurse Station Management'),
			('nursestation_record', 116, 'Record patient data'),
			('menu_nursestation', 117, 'Nurse Station Menu'),
			('dispense_drug', 118, 'Dispense Drug to Patient'),
			('menu_pharmaceutical', 119, 'Pharmaceutical Management'),
			('admission', 120, 'General Admission Management'),
			('admission_create', 121, 'Create Patient Admission'),
			('admission_update', 122, 'Update Patient Admission'),
			('admission_read', 123, 'Read Patient Admission'),
			('admission_delete', 124, 'Delete Patient Admission'),
			('theatre', 125, 'Theatre Management'),
			('theatre_create', 126, 'Create Theatre'),
			('theatre_read', 127, 'Theatre Details'),
			('theatre_update', 128, 'Update Theatre'),
			('theatre_delete', 129, 'Delete Theatre'),
			('theatre_monitor', 130, 'Monitor Patient in Theatre'),
			('dashboard_registered_patients', 131, 'Dashboard for Registered Patients'),
			('dashboard_admitted_patients', 132, 'Dashboard for Admitted Patients'),
			('dashboard_sales', 133, 'Dashboard for Sales'),
			('menu_theatre', 134, 'Theatre Menu'),
			('theatre_read_list', 135, 'Operation Queue'),
			('patientinvoice_custom', 136, 'Patient Invoice Management'),
			('vitalsigns', 137, 'Vital Signs Management'),
			('vitalsigns_create', 138, 'Create Vital Signs'),
			('vitalsigns_read', 139, 'Read Vital Signs'),
			('vitalsigns_update', 140, 'Update Vital Signs'),
			('vitalsigns_delete', 141, 'Delete Vital Signs');