DROP TABLE IF EXISTS _contextManager;
CREATE TABLE _contextManager (
    defaultXValue tinyint not null default 1,
    primary key (defaultXValue)
)engine=innoDB;
INSERT INTO _contextManager(defaultXValue) VALUES(1);
DROP TABLE IF EXISTS _contextLookup;
CREATE TABLE _contextLookup(
	contextId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	symbol CHAR(1) NOT NULL,
	_value CHAR(4) NOT NULL UNIQUE,
	extraFilter VARCHAR(32),
	extraInformation VARCHAR(64),
	flags INT DEFAULT 0,
	PRIMARY KEY(contextId)) engine=innoDB;
INSERT INTO _contextLookup (symbol,_value) VALUES ('A','0000'), ('B','0001'), ('C','0002'), ('D','0010'), ('E','0011'), ('F','0012'), ('G','0020'), ('H','0021'), ('I','0022'), ('J','0100'), ('K','0101'), ('L','0102'), ('M','0110'), ('N','0111'), ('O','0112'), ('P','0120'), ('Q','0121'), ('R','0122'), ('S','0200'), ('T','0201'), ('U','0202'), ('V','0210'), ('W','0211'), ('X','0212'), ('Y','0220'), ('Z','0221'), ('a','0222'), ('b','1000'), ('c','1001'), ('d','1002'), ('e','1010'), ('f','1011'), ('g','1012'), ('h','1020'), ('i','1021'), ('j','1022'), ('k','1100'), ('l','1101'), ('m','1102'), ('n','1110'), ('o','1111'), ('p','1112'), ('q','1120'), ('r','1121'), ('s','1122'), ('t','1200'), ('u','1201'), ('v','1202'), ('w','1210'), ('x','1211'), ('y','1212'), ('z','1220'), ('0','1221'), ('1','1222'), ('2','2000'), ('3','2001'), ('4','2002'), ('5','2010'), ('6','2011'), ('7','2012'), ('8','2020'), ('9','2021'), ('!','2022'), ('@','2100'), ('#','2101'), ('%','2102'), ('&','2110'), ('(','2111'), (')','2112'), ('{','2120'), ('}','2121'), ('[','2122'), (']','2200'), ('<','2201'), ('>','2202'), ('?','2210'), ('+','2211'), ('*','2212'), ('|','2220'), (':','2221'), (';','2222');
DROP TABLE IF EXISTS _contextPosition;
CREATE TABLE _contextPosition(
	cId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	cName VARCHAR(56) NOT NULL UNIQUE,
	cPosition INT NOT NULL UNIQUE,
	caption VARCHAR(96) NOT NULL,
	extraFilter VARCHAR(32),
	extraInformation VARCHAR(64),
	flags INT DEFAULT 0,
	PRIMARY KEY(cId)) engine=innoDB;
	INSERT INTO _contextPosition (cName, cPosition, caption) VALUES 
			('login', 1, 'User Accounts Management'), 
			('login_create', 2, 'Create User Account'),
			('login_read', 3, 'View User Account'), 
			('login_update', 4, 'Update User Account'), 
			('login_delete', 5, 'Delete User Account'),
			('login_search', 6, 'Search User Accounts'),
			('profile', 7, 'General System Settings'),
			('profile_update', 8, 'Update System Settings'), 
			('profile_read', 9, 'View System Settings'),
			('group', 10, 'General Group Operation'),
			('group_create',11, 'Create a User Group'),
			('group_read', 12, 'View a User Group'),
			('group_update', 13, 'Update a User Group'),
			('group_delete', 14, 'Delete a User Group'),
			('group_search', 15, 'Search User Groups'),
			('jobtitle', 16, 'General Jobtitle Operations'),
			('jobtitle_create', 17, 'Create a User Jobtitle'),
			('jobtitle_read', 18, 'View a User Jobtitle'),
			('jobtitle_update', 19, 'Update a User Jobtitle'),
			('jobtitle_delete', 20, 'Delete a User Jobtitle'),
			('jobtitle_search', 21, 'Search User Jobtitles'),
			('menu_mysystem', 22, 'My System Menu'),
			('menu_users', 23, 'System Users'),
			('update_my_login', 24, 'Update My User Accounts'),
			('firewall', 25, 'Firewall/Authorization Management'),
			('firewall_update', 26, 'Update Firewall'),
			('firewall_read', 27, 'View Firewalls'),
			('system_lastresort_donotcare', 28, 'System Decision on Do not care'),
			('systemlogs', 29, 'General System Logs Management'),
			('systemlogs_search', 30, 'Search System Logs'),
			('patient', 31, 'Patient Management'),
			('patient_create', 32, 'Create A Patient'),
			('patient_read', 33, 'Details of A Patient'),
			('patient_update', 34, 'Update Patient'),
			('patient_delete', 35, 'Delete a Patient'),
			('patient_search', 36, 'Search Patients'),
			('servicecategory', 37, 'Service Category Management'),
			('servicecategory_create', 38, 'Create Service Category'),
			('servicecategory_read', 39, 'Details of a Service Category'),
			('servicecategory_update', 40, 'Update Service Category'),
			('servicecategory_delete', 41, 'Delete a Service Category'),
			('servicecategory_search', 42, 'Search Service Categories'),
			('menu_finance', 43, 'Finance Menu'),
			('service', 44, 'Service Management'),
			('service_create', 45, 'Create Service'),
			('service_read', 46, 'Details of a Service'),
			('service_update', 47, 'Update Service'),
			('service_delete', 48, 'Delete a Service'),
			('service_search', 49, 'Search Services'),
			('hospital', 50, 'Hospital Settings Management'),
			('hospital_read', 51, 'Details/View Hospital Settings'),
			('hospital_update', 52, 'Update Hospital Settings'),
			('notificationmanager', 53, 'Notification Manager Services'),
			('notificationmanager_create', 54, 'Create a New Notification Manager'),
			('notificationmanager_read', 55, 'Details/View a Notification Manager'),
			('notificationmanager_update', 56, 'Update a Notification Manager'),
			('notificationmanager_delete', 57, 'Delete a Notification Manager'),
			('notificationmanager_search', 58, 'Search a Notification Manager'),
			('patientinvoice', 59, 'General Patient Invoice Management'),
			('patientinvoice_create', 60, 'Raise/Create Patient Invoice'),
			('patientinvoice_read', 61, 'Deails/View Patient Invoice'),
			('patientinvoice_search', 62, 'Search Patient Invoice'),
			('patientreceipt', 63, 'General Patient Receipt Management'),
			('patientreceipt_create', 64, 'Issue/Create a Patient Receipt'),
			('patientreceipt_read', 65, 'Details/View a Patient Receipt'),
			('patientreceipt_search', 66, 'Search a Patient Receipt'),
			('triage', 67, 'Triage [Vital Signs] Management'),
			('triage_create', 68, 'Triage [Vitals Signs] create or record'),
			('triage_read', 69, 'Triage [Vital Signs] view details'),
			('triage_search', 70, 'Triage [Vital Signs] Search'),
			('systemuser', 71, 'General System User Management'),
			('systemuser_create', 72, 'Create a System User'),
			('systemuser_read', 73, 'Details/View of a System User'),
			('systemuser_update', 74, 'Update a System User'),
			('systemuser_delete', 75, 'Delete a System User'),
			('systemuser_search', 76, 'Search a System User'),
			('medicaldoctor', 77, 'General Medical Doctor Management'),
			('medicaldoctor_create', 78, 'Create or Add a Medical Doctor'),
			('medicaldoctor_read', 79, 'Details/View a Medical Doctor'),
			('medicaldoctor_update', 80, 'Update Medical Doctor data'),
			('medicaldoctor_delete', 81, 'Delete or Remove medical Doctor'),
			('medicaldoctor_search', 82, 'Search Medical Doctor'),
			('medicaldoctor_consult', 83, 'Patient Consultation'),
			('examination', 84, 'Laboratory Examination'),
			('examination_ultrasound', 85, 'Ultra Sound Examination'),
			('examination_xray_plain', 86, 'Plain X-RAY Examination'),
			('examination_wetlab', 87, 'Wet/Chemical Laboratory Examination'),
			('pharmaceuticaldrug', 88, 'General Drugs Management'),
			('pharmaceuticaldrug_create', 89, 'Create a Drug'),
			('pharmaceuticaldrug_read', 90, 'Details/View a Drug'),
			('pharmaceuticaldrug_update', 91, 'Update Drug'),
			('pharmaceuticaldrug_delete', 92, 'Delete or remove a drug'),
			('pharmaceuticaldrug_search', 93, 'Search a Drug'),
			('menu_admission', 94, 'Admission Menu'),
			('ward', 95, 'General Wards Management'),
			('ward_create', 96, 'Create a New Ward'),
			('ward_read', 97, 'Details/View a Ward'),
			('ward_update', 98, 'Update a ward'),
			('ward_delete', 99, 'Delete a ward'),
			('ward_search', 100, 'Search a ward'),
			('room', 101, 'General Rooms Management'),
			('room_create', 102, 'Create a New Room'),
			('room_read', 103, 'Details/View a Room'),
			('room_update', 104, 'Update a Room'),
			('room_delete', 105, 'Delete a Room'),
			('room_search', 106, 'Search a Room'),
			('bed', 107, 'General Beds Management'),
			('bed_create', 108, 'Create a New Bed'),
			('bed_read', 109, 'Details/View a Bed'),
			('bed_update', 110, 'Update a Bed'),
			('bed_delete', 111, 'Delete a Bed'),
			('bed_search', 112, 'Search a Bed'),
			('medicaldoctor_approve_results', 113, 'Approve Examination Results'),
			('medicaldoctor_repeat_examination', 114, 'Repeat Examination Request'),
			('nursestation', 115, 'Nurse Station Management'),
			('nursestation_record', 116, 'Record patient data'),
			('menu_nursestation', 117, 'Nurse Station Menu'),
			('dispense_drug', 118, 'Dispense Drug to Patient'),
			('menu_pharmaceutical', 119, 'Pharmaceutical Management'),
			('admission', 120, 'General Admission Management'),
			('admission_create', 121, 'Create Patient Admission'),
			('admission_update', 122, 'Update Patient Admission'),
			('admission_read', 123, 'Read Patient Admission'),
			('admission_delete', 124, 'Delete Patient Admission'),
			('theatre', 125, 'Theatre Management'),
			('theatre_create', 126, 'Create Theatre'),
			('theatre_read', 127, 'Theatre Details'),
			('theatre_update', 128, 'Update Theatre'),
			('theatre_delete', 129, 'Delete Theatre'),
			('theatre_monitor', 130, 'Monitor Patient in Theatre'),
			('dashboard_registered_patients', 131, 'Dashboard for Registered Patients'),
			('dashboard_admitted_patients', 132, 'Dashboard for Admitted Patients'),
			('dashboard_sales', 133, 'Dashboard for Sales'),
			('menu_theatre', 134, 'Theatre Menu'),
			('theatre_read_list', 135, 'Operation Queue'),
			('patientinvoice_custom', 136, 'Patient Invoice Management'),
			('vitalsigns', 137, 'Vital Signs Management'),
			('vitalsigns_create', 138, 'Create Vital Signs'),
			('vitalsigns_read', 139, 'Read Vital Signs'),
			('vitalsigns_update', 140, 'Update Vital Signs'),
			('vitalsigns_delete', 141, 'Delete Vital Signs');
DROP TABLE IF EXISTS _navigationMenu;
CREATE TABLE _navigationMenu(
	menuId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	menuName VARCHAR(255) NOT NULL,
	pageToGo VARCHAR(255),
	seqno INT DEFAULT 0,
	pId INT UNSIGNED DEFAULT NULL,
	cName VARCHAR(56),
	flags INT DEFAULT 0,
	FOREIGN KEY(pId) REFERENCES _navigationMenu(menuId),
	PRIMARY KEY(menuId)) engine=innoDB;
INSERT INTO _navigationMenu (menuId,menuName,pageToGo,seqno,pId,cName) VALUES (1,'Staff/User Management','',0,NULL,'menu_users'), (2,'Patient Management','',0,NULL,'menu_patients'), (3,'Financial Management','',0,NULL,'finance'), (4,'Patient Flow Management','',0,NULL,'patient_flow'), (5,'Laboratory Management','',0,NULL,'laboratory'), (6,'Admission Management','',0,NULL,'admission'), (7,'Pharmacy Management','',0,NULL,'pharmacy'), (8,'Ward & Admission Management','',0,NULL,'admission'), (9,'User Accounts Management','page=login',0,1,'login'), (10,'Job Title Management','page=jobtitle',0,1,'jobtitle'), (11,'Group Management','page=group',0,1,'group');
DROP TABLE IF EXISTS _systemlogs;
CREATE TABLE _systemlogs(
	logId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	logDate INT NOT NULL DEFAULT 0,
	username VARCHAR(56) NOT NULL,
	contextPosition INT UNSIGNED NOT NULL,
	opname VARCHAR(56) NOT NULL,
	target VARCHAR(96) NOT NULL,
	flags INT DEFAULT 0,
	FOREIGN KEY(contextPosition) REFERENCES _contextPosition(cId),
	PRIMARY KEY(logId)) engine=innoDB;

